config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :portfolios do
    member do
      get "historical_test"
    end
  end

end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  belongs_to :portfolio
end

app/models/activity.rb
# frozen_string_literal: true

class Activity < ApplicationRecord
  belongs_to :market
  has_many :market_moving_averages
  has_many :market_bollinger_bands
  has_many :trading_signals

  scope :history, -> ( portfolio_id, market_id ) { where( market_id: market_id, portfolio_id: portfolio_id ) }
  # for use by technical-analysis gem
  def to_analysis_hash
    {
      id: id || 0,
      date_time: date,
      open: open,
      high: high,
      low: low,
      close: close
    }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def float_of_2_decimal(float_n)
    num = float_n.to_s.split('.')
    num[1] = num.size > 1 ? num[1] = num[1][0..1] : "00"
    num.join(".").to_f
  end
end

app/models/concerns/signalable.rb
# frozen_string_literal: true

module Signalable

  def determine_signal( act, signal )
    if act.trading_signals.empty? || act.trading_signals.detect{ |ts| ts.triggers == signal[:signal] }
      # {
      #   calling_id: id,
      #   signal: signal,
      #   direction: direction.to_s,
      #   notes: notes.blank? ? "" : notes
      # }
      return create_signal( signal[:signal],
                            signal[:direction],
                            act,
                            notes: signal[:notes] )
    end
    nil
  end

  def create_signal( originator, direction, activity, notes: "" )
    action = direction == :long ? 'buy' : 'sell'
    risk = activity.risk( activity.portfolio.account.starting_capital)
    description = <<~MESSAGE
      #{action} #{activity.market.trading_symbol} on #{activity.market.trading_market.upcase}
      at #{activity.close}
      NOTES: #{notes}
    MESSAGE
    {
      action_description: description,
      triggers: originator.to_s,
      direction: TradingSignal.directions[direction],
      activity_id: activity.id
    }
  end

  def alert

  end
end

app/models/market.rb
class Market < ApplicationRecord
  has_and_belongs_to_many :portfolios
  has_many :activities
  has_many :market_moving_averages
  has_many :market_bollinger_bands
  has_many :market_highs

  enum period: [ :day, :week, :hour, :tick ]

  after_find :tick_update

  def risk( account_value: nil, percentage: 0.02, atr_multiplier: 2 )
    raise StandardError.new( "No Activities loaded" ) if activities.size.zero?

    unless account_value
      account_value = portfolio.account.starting_capital/100
    end

    normalized_tick = ( 1 / tick_size ) * tick_value
    atr_val = activities&.order( date: :asc ).last&.atr || 0
    tick_multiple = atr_multiplier * atr_val * normalized_tick
    result = {
      account_value: account_value,
      risk_dollars: percentage * account_value,
      current_atr:  float_of_2_decimal( atr_val ),
      atr_tick_stop: float_of_2_decimal( atr_multiplier * atr_val ),
      current_atr_dollars: float_of_2_decimal( atr_val * normalized_tick ),
      atr_dollar_risk: float_of_2_decimal( tick_multiple )
    }
    if tick_multiple > 0
      result.merge!( contracts: float_of_2_decimal( ( percentage * account_value ) / tick_multiple ),
                     units: ( ( percentage * account_value) / tick_multiple ).floor )
    end
    result
  end

  def tick_update
    return if tick_size.present? && tick_value.present?

    result = TickMapper.find( trading_market.to_sym, nil )
    self.tick_value = result[:tick_value]
    self.tick_size = result[:tick_size]
    save!
  end
end

app/models/market_bollinger_band.rb
# frozen_string_literal: true

class MarketBollingerBand < ApplicationRecord
  belongs_to :activity
  belongs_to :market
  belongs_to :portfolio
end

app/models/market_high.rb
# frozen_string_literal: true

class MarketHigh < ApplicationRecord
  belongs_to :activity
  belongs_to :market
  belongs_to :portfolio
end

app/models/market_moving_average.rb
# frozen_string_literal: true

class MarketMovingAverage < ApplicationRecord
  belongs_to :market
  belongs_to :portfolio
  belongs_to :activity

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_and_belongs_to_many :markets
    has_and_belongs_to_many :rules
    has_many :activities
    has_many :markets
    has_many :accounts
    has_many :trading_signals, through: :activities, class_name: 'TradingSignal'
end

app/models/position.rb
# frozen_string_literal: true

class Position < ApplicationRecord
  belongs_to :portfolio

end

app/models/rule.rb
class Rule < ApplicationRecord
  has_and_belongs_to_many :portfolios
  has_many :signals

  enum category: [ :entry, :exit, :money, :confirmation_entry, :confirmation_exit ]

  def tool_map
  end
end

app/models/trading_signal.rb
class TradingSignal < ApplicationRecord
  belongs_to :activity

  enum direction: [ :long, :short ]

  def portfolio
    activity.portfolio
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController

  def index
    @portfolios = Portfolio.all
  end

  def create
    @portfolio = Portfolio.create( portfolio_params )

    redirect_to portfolios_path
  end

  def show
    @portfolio = Portfolio.find( params[:id] )
    @markets = Market.all
  end

  def destroy
    @portfolio = Portfolio.find( params[:id] )
    @portfolio.destroy

    redirect_to portfolios_path
  end

  def historical_test
    context = HistoricalTest.call( portfolio_id: @params[:id] )

    redirect_to portfolio_path( id: params[:id] )
  end



  def update
    @portfolio = Portfolio.find( params[:id] )
    @portfolio.name = portfolio_params[:name]
    @portfolio.description = portfolio_params[:description]
    @portfolio.market_ids = portfolio_params[:markets]

    flash[:notice] = "portfolio updated" if @portfolio.save
    redirect_to portfolio_path( id: params[:id] )
  end



  private
    def portfolio_params
      params.require(:portfolio).permit( :name,
                                         :description,
                                         markets: [] )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Analyzer
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
  body.d-flex.flex-column.h-100
    header
      /! Fixed navbar
      nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
        a.navbar-brand href="#"  Fixed navbar
        button.navbar-toggler aria-controls="navbarCollapse" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarCollapse" data-toggle="collapse" type="button"
          span.navbar-toggler-icon
        #navbarCollapse.collapse.navbar-collapse
          ul.navbar-nav.mr-auto
            li.nav-item.active
              = link_to "Portfolios", portfolios_url, :class=>'nav-link'
            li.nav-item
              a.nav-link href="#"  Markets
            li.nav-item
              a.nav-link.disabled aria-disabled="true" href="#" tabindex="-1"  Signals
          form.form-inline.mt-2.mt-md-0
            input.form-control.mr-sm-2 aria-label="Search" placeholder="Search" type="text" /
            button.btn.btn-outline-success.my-2.my-sm-0 type="submit"  Search
    /! Begin page content
    main.flex-shrink-0 role="main"
      .container
        - if flash[:notice]
          .notice
            = flash[:notice]
      .container
        = yield

app/views/portfolios/index.html.slim
h3 Portfolios
= form_for Portfolio.new do |f|
  .row
    .col
      = f.text_field :name
    .col
      = f.text_field :description
    .col
      = submit_tag "Save", data: { disable_with: "Please wait..." }
.row style="margin:15px"
  .col
    strong
      = "name"
  .col
    strong
      = "description"
  .col
    strong
      = "# markets"
  .col
    strong
      = "actions"
- @portfolios.each do |port|
  .row.bg-dark.text-white
    .col
      = port.name
    .col
      = port.description
    .col
      = port.markets.count
    .col
      = link_to 'edit', portfolio_path( id: port.id )
      = " - "
      = link_to "delete", port, method: :delete

app/views/portfolios/show.html.slim
.container
  h3 Portfolio #{@portfolio.id} : #{@portfolio.name}
  = form_for @portfolio do |f|
    = hidden_field_tag :id, @portfolio.id
    .row style="margin:15px"
      .col
        = f.text_field :name
      .col
        = f.text_field :description
      .col
        = submit_tag "Update"
    .row.alert.alert-success style="margin:15px"
      .container
        - @portfolio.rules.each do |rule|
          .row
            .col
              = rule.name
            .col
              = rule.category
      .col
        = link_to "assign rules"
    .row
      .container.bg-dark.text-white
        .row
          .col
            h5
              ="markets"
          .col
            - @markets.each do |mkt|
              .row
                .col
                  span
                    = label_tag( "market_#{mkt.trading_symbol}", mkt.trading_symbol )
                    = check_box_tag('portfolio[markets][]', mkt.id, @portfolio.market_ids&.include?( mkt.id ), :id => "market_#{mkt.trading_symbol}")
                .col
                  = mkt.trading_market